export const CLOSE_VENUE_VIEWER = 'CLOSE_VENUE_VIEWER';
export const FETCH_VENUES = 'FETCH_VENUES';
export const RECIEVED_VENUES = 'RECIEVED_VENUES';
export const RECIEVED_VENUES_FAILED = 'RECIEVED_VENUES_FAILED';
export const SELECT_VENUE = 'SELECT_VENUE';
